# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
    os: ubuntu-22.04
    tools:
        python: "3.12"
    commands:
        # Install Poetry and configure it to not use virtual environments
        - pip install poetry
        - poetry config virtualenvs.create false
        # Install all dependencies including mkdocs and mkdocs-material
        - poetry install --with docs
        # Build the documentation with mkdocs
        - poetry run mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file mkdocs.yml


# Build documentation in the docs/ directory with MkDocs
mkdocs:
    configuration: mkdocs.yml
# Optionally declare the Python requirements required to build your docs
# python:
#   install:
#   - requirements: docs/requirements.txt
