"""Top-level package for NanofinderParser.

Parse and process Raman and photoluminescence (PL) data files generated by Nanofinder instruments.
"""

__author__ = """Pablo Solís-Fernández"""
__email__ = "psolsfer@gmail.com"
__version__ = "0.7.0"

from nanofinderparser.load import (
    load_mdt,
    load_mdt_file,
    load_mdt_folder,
    load_mdt_images,
    load_smd,
    load_smd_folder,
)
from nanofinderparser.samples import (
    SAMPLES,
    SampleInfo,
    SampleName,
    sample_mapping,
    sample_spec,
)
from nanofinderparser.synthetic import (
    BaselineSpec,
    InstrumentSpec,
    MappingSpec,
    MapSpec,
    NoiseSpec,
    PeakSpec,
    SpectralAxisSpec,
    build_mapping,
    build_spectra,
    create_smd,
    map_band,
    map_blob,
    map_disk,
    map_product,
    map_ramp,
)
from nanofinderparser.write import write_smd

__all__ = [
    "SAMPLES",
    "BaselineSpec",
    "InstrumentSpec",
    "MapSpec",
    "MappingSpec",
    "NoiseSpec",
    "PeakSpec",
    "SampleInfo",
    "SampleName",
    "SpectralAxisSpec",
    "build_mapping",
    "build_spectra",
    "create_smd",
    "load_mdt",
    "load_mdt_file",
    "load_mdt_folder",
    "load_mdt_images",
    "load_smd",
    "load_smd_folder",
    "map_band",
    "map_blob",
    "map_disk",
    "map_product",
    "map_ramp",
    "sample_mapping",
    "sample_spec",
    "write_smd",
]
